debug: True
foreground: True
log_filename: /tmp/xivo-auth.log

rest_api:
  listen: 0.0.0.0
  port: 9497
  cors:
    enabled: True
    allow_headers: Content-Type, authorization

enabled_plugins:
  - mock
  - broken_init
  - broken_verify_password

amqp:
  uri: amqp://guest:guest@rabbitmq:5672/
  exchange_name: xivo
  exchange_type: topic

consul:
  host: localhost
  port: 8500
  token: 'the_one_ring'
